import { ConditionalSidebar } from "@/components/dashboard/sidebar/conditional-sidebar";
import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/light-dark-toggle/theme-provider";
import "@mantine/core/styles.css";
import { MantineProvider } from "@mantine/core";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RandevuCo",
  description: "Generated by CazelDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
            <ConditionalSidebar>
              {children}
              <Toaster />
            </ConditionalSidebar>
          </ThemeProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
